media_folder: static/img
public_folder: /img

local_backend: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "blog"
    fields:
      - { label: "Title", name: "title", widget: "string" }
